version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app:delegated
      - packs:/app/public/packs
      - bundle:/usr/local/bundle
    depends_on:
      - pgsql
    tty: true
    stdin_open: true
    environment:
      - RAILS_ENV=development
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bin/dev"

  pgsql:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
  packs:
  bundle:
  postgres:
